add lesson3 tooltip solution
js-tasks-ru/htmlcss-20230911-4_loramisautova pull request #10
Opened 2023-10-02 00:25 UTC by Loramisautova

2023-10-02 00:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-02 19:32 UTC, GSemikozov requested changes

2023-10-02 19:32 UTC, GSemikozov commented on assets/css/main.css
> +    overflow: hidden
на уровне main это точно нам не нужно)

2023-10-05 20:38 UTC, GSemikozov approved these changes

2023-10-05 20:39 UTC, merged