add lesson3 modal solution
js-tasks-ru/htmlcss-20230911-4_loramisautova pull request #11
Opened 2023-10-02 00:50 UTC by Loramisautova

2023-10-02 00:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-02 19:34 UTC, GSemikozov requested changes

2023-10-02 19:34 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    background-color: #C4C4C4;
зададим через rgba

2023-10-02 19:34 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    opacity: 0.5;
это удалим

2023-10-02 19:34 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal {
это элемент блока .modal__window

2023-10-02 19:34 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
и тогда здесь fixed уже не надо, можно absolute

2023-10-02 19:34 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    z-index: 100;
лишнее, у родителя уже есть

2023-10-02 19:34 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal-close {
переписать на класс по БЭМ

2023-10-02 19:34 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal-close svg {
и тут

2023-10-02 19:34 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal-overlay {
это стили блока - .modal

2023-10-02 19:34 UTC, GSemikozov commented on 05-lection3/02-modal/index.js
> +    const overlay = document.getElementById("modal-overlay");
лишнее (см ниже)

2023-10-05 20:40 UTC, GSemikozov approved these changes

2023-10-05 20:40 UTC, merged