add component page layout grid
js-tasks-ru/htmlcss-20230911-4_loramisautova pull request #13
Opened 2023-10-05 02:42 UTC by Loramisautova

2023-10-05 20:47 UTC, GSemikozov requested changes
конфликт

2023-10-05 20:47 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__component-title {
лучше не привязываться к конкретной странице - иначе теряем универсальность, этот элемент может использоваться и на других страницах. Как вариант - .footer__info

2023-10-05 20:47 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__component-content {
это лишнее, поведение блока пусть будет одинаковым на двух страницах

2023-10-05 20:47 UTC, GSemikozov commented on pages/page/page.css
> +.page__component {
лучше через модификатор .page_component

2023-10-05 20:47 UTC, GSemikozov commented on pages/template.html
> +      <div class='page__component'>
`page page_component`

2023-10-11 04:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-11 04:52 UTC, Loramisautova commented on components/footer/footer.css
> +.footer__component-content {
Теперь отступы страницы компонента не соответствует макету, это ок?

2023-10-11 20:40 UTC, GSemikozov requested changes

2023-10-11 20:40 UTC, GSemikozov commented on components/menu/menu.css
> +.menu__item-active {
`.menu__item_active`

2023-10-22 18:35 UTC, GSemikozov approved these changes

2023-10-22 18:35 UTC, merged