add background image
js-tasks-ru/htmlcss-20230911-4_loramisautova pull request #16
Opened 2023-10-11 04:47 UTC by Loramisautova

2023-10-11 04:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-11 20:36 UTC, GSemikozov requested changes

2023-10-11 20:36 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (min-width: 400px) {
лишний медиа-запрос, эта картинка будет стоять по умолчанию, а переопределим - уже в 768

2023-10-17 00:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-22 18:30 UTC, GSemikozov approved these changes

2023-10-22 18:30 UTC, merged