add accordion
js-tasks-ru/htmlcss-20230911-4_loramisautova pull request #5
Opened 2023-09-20 15:17 UTC by Loramisautova

Accordion task of module 3

2023-09-20 15:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-20 20:05 UTC, GSemikozov requested changes

2023-09-20 20:05 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +body {
глобальные стили никогда не описываем в файлах стилей компонентов) удалим.

2023-09-20 20:05 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__container {
это как я понял на самом деле класс блока - .accordion

2023-09-20 20:05 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
лишнее ограничение

2023-09-21 20:47 UTC, GSemikozov approved these changes

2023-09-21 20:47 UTC, merged